language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t crownkira/react-test -f ./client/Dockerfile.dev ./client

# test running section
script:
  - docker run -e CI=true crownkira/react-test npm test

# after test success
after_success:
  - docker build -t crownkira/multi-client ./client
  - docker build -t crownkira/multi-nginx ./nginx
  - docker build -t crownkira/multi-server ./server
  - docker build -t crownkira/multi-worker ./worker
  # Log in to the docker CLI
  # login in one single command
  # retrieve docker password, pass it to the standard in of the next process
  # input to the next command
  # --password-stdin: Take the password from stdin
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push crownkira/multi-client
  - docker push crownkira/multi-nginx
  - docker push crownkira/multi-server
  - docker push crownkira/multi-worker
